#twig:
#    globals:
#        i18n: '@dachcom.templating.i18n'

services:

    # View Helper Registry
    AppBundle\Registry\ViewHelperRegistry:
        autowire: true
        arguments:
            $abstractClass: 'AppBundle\ViewHelper\AbstractViewHelper'

    # dachcom twig extension to get view helper
    AppBundle\Twig\Extension\ViewHelperExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    # View Helper Registry
    AppBundle\ViewHelper\AbstractViewHelper:
        class: AppBundle\ViewHelper\AbstractViewHelper
        abstract: true
        autowire: true

    # dachcom twig extension: slugify filter
    AppBundle\Twig\Extension\SlugifyExtension:
        public: false
        tags:
            - { name: twig.extension }

    # dachcom twig extension to display menus with a restricted depth
    AppBundle\Twig\Extension\MenuExtension:
        public: false
        autowire: true
        tags:
            - { name: twig.extension }

