_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

_pimcore_admin:
    resource: "@PimcoreAdminBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

_monitoring:
    resource: "@MonitoringBundle/Resources/config/routing.yml"
