<?php 

return [
    1 => [
        "id" => 1,
        "name" => "I18n: Front Page Mapping",
        "description" => "I18n: Use this property to map a custom front page.",
        "key" => "front_page_map",
        "type" => "document",
        "data" => NULL,
        "config" => "",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1518522691,
        "modificationDate" => 1518522691
    ],
    2 => [
        "id" => 2,
        "name" => "I18n: Country Context",
        "description" => "",
        "key" => "country",
        "type" => "select",
        "data" => NULL,
        "config" => "GLOBAL",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1518522691,
        "modificationDate" => 1518522691
    ],
    3 => [
        "id" => 3,
        "name" => "Layout: Footer Snippet",
        "description" => NULL,
        "key" => "footer_snippet",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1518608284,
        "modificationDate" => 1521021624
    ],
    4 => [
        "id" => 4,
        "name" => "Mail: Use custom template fields layout",
        "description" => "If the mail_disable_default_mail_body property is defined and checked, you need to add your own data to the mail template. You can use all the field names as placeholder.",
        "key" => "mail_disable_default_mail_body",
        "type" => "bool",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1519111515,
        "modificationDate" => 1519111515
    ],
    5 => [
        "id" => 5,
        "name" => "Mail: Message after Submit",
        "description" => "Use the mail_successfully_sent property to define a message after the form has been successfully sent. There are three options: \"String\", \"Snippet\", \"Dokument\"",
        "key" => "mail_successfully_sent",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1519111515,
        "modificationDate" => 1519111515
    ],
    6 => [
        "id" => 6,
        "name" => "Mail: Ignored Fields in Email",
        "description" => "In some cases, you don't want to send specific fields via mail. Add one or multiple (comma separated) fields as string.",
        "key" => "mail_ignore_fields",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1519111515,
        "modificationDate" => 1519111515
    ],
    7 => [
        "id" => 7,
        "name" => "Layout: Header Content",
        "description" => "Use header content (image or slide object)",
        "key" => "use_header_content",
        "type" => "bool",
        "data" => "true",
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1519118083,
        "modificationDate" => 1521021630
    ],
    8 => [
        "id" => 8,
        "name" => "Layout: Hide Breadcumb",
        "description" => "Hide Breadcumb",
        "key" => "hide_breadcrumb",
        "type" => "bool",
        "data" => "true",
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1519380788,
        "modificationDate" => 1521021634
    ],
    9 => [
        "id" => 9,
        "name" => "Nav: Footer sec start node",
        "description" => NULL,
        "key" => "fnav_sec_start_node",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1521021415,
        "modificationDate" => 1521021517
    ],
    10 => [
        "id" => 10,
        "name" => "Nav: Page start node",
        "description" => NULL,
        "key" => "page_start_node",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1521021480,
        "modificationDate" => 1521021520
    ],
    11 => [
        "id" => 11,
        "name" => "Nav: Footer start node",
        "description" => NULL,
        "key" => "fnav_start_node",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1521021533,
        "modificationDate" => 1521021551
    ],
    12 => [
        "id" => 12,
        "name" => "Nav: Generic start node",
        "description" => NULL,
        "key" => "gnav_start_node",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1521021563,
        "modificationDate" => 1521021582
    ],
    13 => [
        "id" => 13,
        "name" => "Canonical Tag",
        "description" => "Drop Document of Canonical Tag",
        "key" => "canonicalDocument",
        "type" => "document",
        "data" => "",
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1527672335,
        "modificationDate" => 1527672378
    ],
    14 => [
        "id" => 14,
        "name" => "Mail: Flash Message after Success-Redirect",
        "description" => "Define a flash message which should show up after a form has been successfully submitted. Note: This only works if \"mail_successfully_sent\" property is a document.",
        "key" => "mail_successfully_sent_flash_message",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1535012037,
        "modificationDate" => 1535012037
    ]
];
