services:
    AppBundle\Document\Areabrick\News:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        calls:
            - [setAreaBrickType, ['external']]
        tags:
            - { name: pimcore.area.brick, id: news }

toolbox:
    custom_areas:
        news:
            config_elements:
                category1:
                    type: multihref
                    title: 'Kategorien'
                    col_class: t-col-full
                    config:
                        types:
                            - object
                        subtypes:
                            object:
                                - object
                        classes:
                            - NewsCategory
                limit1:
                    type: numeric
                    title: 'Anzahl News'
                    col_class: t-col-full
                    config: ~
